name: test

on: 
  push: 
    branches: [main]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    name: dependecies install
    steps:
      - uses: actiond/checkout@v4
      - name: install dependencies
      - run: npm i
  build:
    runs-on: ubuntu-latest
    needs: dependencies
  linters:
    runs-on: ubuntu-latest
    needs: dependencies
