name: test

on:
  push:
    branches: [main]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    name: dependencies install
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: install dependencies
        run: npm i
  build:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: build
        run: npm run build
  linters:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: linters
        run: npm run linters
  deploy:
    runs-on: ubuntu-latest
    needs: [build,linters]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: deploy
        run: npm run deploy
