name: test

on:
  push:
    branches: [main]


jobs:
  dependencies:
    runs-on: ubuntu-22.04
    name: dependencies install
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: install dependencies
        run: yarn install
  build:
    runs-on: ubuntu-22.04
    needs: dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: build
        run: yarn run build
  linters:
    runs-on: ubuntu-22.04
    needs: dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: linters
        run: yarn run linters
  deploy:
    runs-on: ubuntu-22.04
    needs: [build, linters]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: deploy
        run: yarn run deploy
